from raglab.instruction_lab.instruction_lab import ALGORITHM_INSTRUCTIONS
from raglab.instruction_lab.dataset_instructions import DATA_INSTRUCTIONS
from raglab.instruction_lab.system_instructions import SYSTEM_INSTRUCTION